query SwissTournaments {
  tournaments(query: {
    perPage: 80
    page: $page
    filter: {
      countryCode: "CH"
      beforeDate: $beforeDate
      afterDate: $afterDate
      videogameIds: [
        1386,
      ]
    }
    sort: startAt
  }) {
    pageInfo {
        totalPages
    }
    nodes {
      events {
        id
        startAt
        slug
        isOnline
        videogame {
          id
        }
      }
    }
  }
}